import { accordionThiefSkills } from './skills/AccordionThief';
import { hobopolisSkills } from './skills/Hobopolis';
import { pastamancerSkills } from './skills/Pastamancer';
import { questSkills } from './skills/Quests';
import { sealClubberSkills } from './skills/SealClubber';
import { Classes, type Skill, SkillSource } from './SkillType';

export const all_skills: Skill[] = [
	...accordionThiefSkills,
	...hobopolisSkills,
	...pastamancerSkills,
	...questSkills,
	...sealClubberSkills,
	{
		name: 'Smooth Movement',
		notes: '-5% combat',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 14,
		sc: true,
		hc: true,
		tags: ['misc', 'evergreen'],
		year: null
	},
	{
		name: 'Advanced Saucecrafting',
		notes: 'Summons 3 scrumptious reagents',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 5,
		sc: true,
		hc: true,
		tags: ['turns', 'misc', 'evergreen'],
		year: null
	},
	{
		name: 'Saucemaven',
		notes: '3 turns to saucy food, 5 if a mys class',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 11,
		sc: true,
		hc: true,
		tags: ['turns', 'evergreen'],
		year: null
	},
	{
		name: 'The Way of Sauce',
		notes: 'Summons 2 scrumptious reagents, unlocks recipes',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 15,
		sc: true,
		hc: true,
		tags: ['turns', 'misc', 'evergreen'],
		year: null
	},
	{
		name: 'Bowl Full of Jelly',
		notes: 'Summons a 1-fullness epic food',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['turns'],
		year: 2020
	},
	{
		name: 'Eye and a Twist',
		notes: 'Summons a 1-potency epic booze',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['turns'],
		year: 2020
	},
	{
		name: 'Grab a Cold One',
		notes: 'Summons a 1-potency epic booze',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['turns', 'evergreen'],
		year: null
	},
	{
		name: 'Spaghetti Breakfast',
		notes: 'Summons a 1-fullness epic food',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['turns', 'evergreen'],
		year: null
	},
	{
		name: 'Lock Picking',
		notes: 'Summons a hero key',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['misc'],
		year: 2020
	},
	{
		name: 'Mad Looting Skillz',
		notes: '20% item',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 8,
		sc: true,
		hc: true,
		tags: ['item', 'evergreen'],
		year: null
	},
	{
		name: 'Amphibian Sympathy',
		notes: '5 familiar weight',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 5,
		sc: true,
		hc: true,
		tags: ['familiar', 'xp', 'item', 'meat', 'evergreen'],
		year: null
	},
	{
		name: 'Empathy of the Newt',
		notes: '5 familiar weight / 5 turns',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 8,
		sc: true,
		hc: true,
		tags: ['familiar', 'xp', 'item', 'meat', 'evergreen'],
		year: null
	},
	{
		name: 'Superhuman Cocktailcrafting',
		notes: "Summons 2 AC ingredients, access to Nash Crosby's still",
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 15,
		sc: true,
		hc: true,
		tags: ['turns', 'misc', 'evergreen'],
		year: null
	},
	{
		name: 'The Long View',
		notes: '3 rollover adventures',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 12,
		sc: true,
		hc: true,
		tags: ['turns', 'evergreen'],
		year: null
	},
	{
		name: 'Brain Games',
		notes: '3 rollover adventures',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['turns', 'evergreen'],
		year: null
	},
	{
		name: 'Torso Awareness',
		notes: 'Wear shirts',
		source: SkillSource.QUEST,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['xp', 'combat', 'evergreen'],
		year: null
	},
	{
		name: 'Patient Smile',
		notes: '1 mus substat/combat',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 14,
		sc: false,
		hc: false,
		tags: ['xp', 'evergreen'],
		year: null
	},
	{
		name: 'Wry Smile',
		notes: '1 mys substat/combat',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 13,
		sc: false,
		hc: false,
		tags: ['xp', 'evergreen'],
		year: null
	},
	{
		name: 'Dimples, How Merry!',
		notes: '1 substat/combat',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['xp'],
		year: 2020
	},
	{
		name: "Drescher's Annoying Noise",
		notes: '10 ML / 20 turns',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['xp', 'evergreen'],
		year: null
	},
	{
		name: 'Ancient Crymbo Lore',
		notes: '3 substat/combat in December',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['xp'],
		year: 2021
	},
	{
		name: 'Powers of Observatiogn',
		notes: '10% item',
		source: SkillSource.QUEST,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['item', 'evergreen'],
		year: null
	},
	{
		name: '20/20 Vision',
		notes: '10% item',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['item', 'evergreen'],
		year: null
	},
	{
		name: "Singer's Faithful Ocelot",
		notes: '10% item / 10 turns',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['item', 'evergreen'],
		year: null
	},
	{
		name: 'Natural Born Scrabbler',
		notes: '5% item',
		source: SkillSource.HOBOPOLIS,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['item', 'evergreen'],
		year: null
	},
	{
		name: 'Sensitive Fingers',
		notes: '10% pickpocket',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 14,
		sc: false,
		hc: false,
		tags: ['item', 'evergreen'],
		year: null
	},
	{
		name: 'Always Never Not Guzzling',
		notes: '25% booze',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['item'],
		year: 2020
	},
	{
		name: 'Curse of Weaksauce',
		notes: 'Delevels 3%/round',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 12,
		sc: true,
		hc: true,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Itchy Curse Finger',
		notes: 'Curses stagger',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 8,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Tao of the Terrapin',
		notes: 'Doubles power of hat and pants',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 15,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Saucestorm',
		notes: 'Cold and hot damage spell',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 5,
		sc: true,
		hc: true,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Skin of the Leatherback',
		notes: 'level/2 damage reduction',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 2,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Conspiratorial Whispers',
		notes: 'Instant delevel and damage per familiar weight',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Astral Shell',
		notes: '80 damage absorption and 1 all res / 5 turns',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 12,
		sc: false,
		hc: false,
		tags: ['combat', 'misc', 'evergreen'],
		year: null
	},
	{
		name: 'Ghostly Shell',
		notes: '80 damage absorption / 5 turns',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 4,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Elemental Saucesphere',
		notes: '2 all res / 5 turns',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 4,
		sc: false,
		hc: false,
		tags: ['combat', 'misc', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Master Saucier',
		notes: '10% spell damage',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 10,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Slimy Sinews',
		notes: 'max HP',
		source: SkillSource.THE_SLIME_TUBE,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Shadow Noodles',
		notes: 'Stun for 3-5 rounds and delevels',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Hero of the Half-Shell',
		notes: 'Shields reduce damage with muscle rather than moxie',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 14,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Abs of Tin',
		notes: '10% max HP',
		source: SkillSource.HOBOPOLIS,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Cold-Blooded Fearlessness',
		notes: '2 spooky res',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 13,
		sc: false,
		hc: false,
		tags: ['combat', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Diminished Gag Reflex',
		notes: '2 stench res',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 13,
		sc: false,
		hc: false,
		tags: ['combat', 'misc', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Heart of Polyester',
		notes: '2 sleaze res',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 13,
		sc: false,
		hc: false,
		tags: ['combat', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Splashdance',
		notes: 'Instant heal',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Saucy Salve',
		notes: 'Instant heal',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 2,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Jalapeño Saucesphere',
		notes: '3 damage resistance and damage attacker / 5 turns',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 7,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Irrepressible Spunk',
		notes: '5% max HP and MP',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 14,
		sc: false,
		hc: false,
		tags: ['combat', 'mp', 'evergreen'],
		year: null
	},
	{
		name: 'Saucegeyser',
		notes: 'Cold or hot damage',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 11,
		sc: true,
		hc: true,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Gnomish Hardigness',
		notes: '5% max HP',
		source: SkillSource.QUEST,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Song of Sauce',
		notes: '50 hot damage, hot spell damage, 100% spell damage / 10 turns',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Song of the North',
		notes: '50 cold damage, 100% weapon damage / 10 turns',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Shell Up',
		notes: 'Blocks and deals 10% of muscle as damage',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 5,
		sc: false,
		hc: false,
		tags: ['combat', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Sauceshell',
		notes: 'Blocks and deals 80 hot damage',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Scarysauce',
		notes: '2 cold and sleaze res and damages attackers / 5 turns',
		source: SkillSource.QUEST,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Club Earth',
		notes: 'Staggering attack',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Disco Fever',
		notes: '10% moxie and 10 ranged damage / 10 turns',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 13,
		sc: false,
		hc: false,
		tags: ['combat', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Reptilian Fortitude',
		notes: '30 max HP / 5 turns',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 10,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Spiky Shell',
		notes: '4 damage to attackers / 5 turns',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 9,
		sc: false,
		hc: false,
		tags: ['combat', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Stiff Upper Lip',
		notes: '10 DR',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 3,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Disco Smirk',
		notes: '10 moxie / 10 turns',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 8,
		sc: false,
		hc: false,
		tags: ['combat', 'evergreen'],
		year: null
	},
	{
		name: 'Visit your Favorite Bird',
		notes: '100% meat, 150% initiative, 50% item, or -11% combat / 20 turns',
		source: SkillSource.IOTM,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['misc'],
		year: 2020
	},
	{
		name: 'CLEESH',
		notes: 'Turns the monster into one of various amphibians',
		source: SkillSource.QUEST,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['misc', 'evergreen'],
		year: null
	},
	{
		name: 'Dead Nostrils',
		notes: '1  stench res, 1 stench spell damage',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['misc', 'evergreen'],
		year: null
	},
	{
		name: 'Thick-Skinned',
		notes: '10 max HP and MP',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['mp', 'evergreen'],
		year: null
	},
	{
		name: 'Wisdom of the Elder Tortoises',
		notes: '50% max MP',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 11,
		sc: false,
		hc: false,
		tags: ['mp', 'evergreen'],
		year: null
	},
	{
		name: 'Slimy Synapses',
		notes: 'max MP',
		source: SkillSource.THE_SLIME_TUBE,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['mp', 'evergreen'],
		year: null
	},
	{
		name: 'Marginally Insane',
		notes: '10% max MP',
		source: SkillSource.HOBOPOLIS,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['mp', 'evergreen'],
		year: null
	},
	{
		name: 'Blood Sugar Sauce Magic',
		notes: '10% max MP and -10% max HP or 30% for Saucerors',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 15,
		sc: false,
		hc: false,
		tags: ['mp', 'evergreen'],
		year: null
	},
	{
		name: 'Cosmic Ugnderstanding',
		notes: '5% max MP',
		source: SkillSource.QUEST,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['mp', 'evergreen'],
		year: null
	},
	{
		name: 'Nimble Fingers',
		notes: '20% meat',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 6,
		sc: false,
		hc: false,
		tags: ['meat', 'evergreen'],
		year: null
	},
	{
		name: 'Inner Sauce',
		notes: '1 MP/adventure or 3 for saucerors',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 4,
		sc: false,
		hc: false,
		tags: ['meat', 'evergreen'],
		year: null
	},
	{
		name: 'Expert Panhandling',
		notes: '10% meat or 15% with a saucepan',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 3,
		sc: false,
		hc: false,
		tags: ['meat', 'evergreen'],
		year: null
	},
	{
		name: 'Gnefarious Pickpocketing',
		notes: '10% meat',
		source: SkillSource.QUEST,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['meat', 'evergreen'],
		year: null
	},
	{
		name: 'Disco Leer',
		notes: '10% meat / 10 turns',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 15,
		sc: false,
		hc: false,
		tags: ['meat', 'evergreen'],
		year: null
	},
	{
		name: 'Thrift and Grift',
		notes: '10% meat',
		source: SkillSource.HOBOPOLIS,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['meat', 'evergreen'],
		year: null
	},

	{
		name: 'Overdeveloped Sense of Self Preservation',
		notes: '20% initiative',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 2,
		sc: false,
		hc: false,
		tags: ['init', 'evergreen'],
		year: null
	},
	{
		name: 'Slimy Shoulders',
		notes: 'initiative',
		source: SkillSource.THE_SLIME_TUBE,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['init', 'evergreen'],
		year: null
	},
	{
		name: "Walberg's Dim Bulb",
		notes: '10% initiative / 10 turns',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['init', 'evergreen'],
		year: null
	},
	{
		name: 'Song of Slowness',
		notes: '50% initiative / 10 turns',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['init', 'evergreen'],
		year: null
	},
	{
		name: 'Blessing of the Storm Tortoise',
		notes: '5% initiative and 10 max MP / 10 turns',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 11,
		sc: false,
		hc: false,
		tags: ['mp', 'init', 'evergreen'],
		year: null
	},
	{
		name: 'Ambidextrous Funkslinging',
		notes: 'Two combat items/round',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 12,
		sc: true,
		hc: true,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Icy Glare',
		notes: '10 cold damage, 10 cold spell damage / 10 turns',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 3,
		sc: false,
		hc: false,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Dirge of Dreadfulness',
		notes: '12 spooky damage, 12 spooky spell damage / AT turns',
		source: SkillSource.QUEST,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Snarl of the Timberwolf',
		notes: '10 spooky damage / 10 turns',
		source: SkillSource.QUEST,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Testudinal Teachings',
		notes: '1 familiar xp/6 combats',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 9,
		sc: true,
		hc: true,
		tags: ['familiar', 'marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Disco Nap',
		notes: 'Heals 20 HP and removes debuffs. One free campsite rest/day',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 3,
		sc: false,
		hc: false,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Adventurer of Leisure',
		notes: 'Disco Nap heals 40 HP and 3 free rests',
		source: SkillSource.CLASS,
		class: Classes.DISCO_BANDIT,
		level: 11,
		sc: false,
		hc: false,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Splattersmash',
		notes: 'Group damage based on muscle',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Song of Bravado',
		notes: '15% all attributes',
		source: SkillSource.DREADSYLVANIA,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Impetuous Sauciness',
		notes: '5 turns to sauceror buffs',
		source: SkillSource.CLASS,
		class: Classes.SAUCEROR,
		level: 12,
		sc: false,
		hc: false,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: 'Armorcraftiness',
		notes: 'Allows you to craft more stuff',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 5,
		sc: true,
		hc: false,
		tags: ['marginal', 'evergreen'],
		year: null
	},
	{
		name: "Long Winter's Nap",
		notes: '5 free rests/day',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['marginal'],
		year: 2020
	},
	{
		name: 'Chubby and Plump',
		notes: 'Summons one "Chubby & Plump" bar, 50% max HP and MP / 50 turns',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: false,
		hc: false,
		tags: ['marginal'],
		year: 2020
	},
	{
		name: 'Pizza Lover',
		notes: 'Ode for pizzas',
		source: SkillSource.CLASS,
		class: Classes.TURTLE_TAMER,
		level: 4,
		sc: true,
		hc: true,
		tags: ['turns', 'evergreen'],
		year: null
	},
	{
		name: 'Old-School Cocktailcrafting',
		notes: '3 free cocktailcrafts / day',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['marginal'],
		year: 2023
	},
	{
		name: 'Elf Guard Cooking',
		notes: '3 free cooks / day',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['marginal'],
		year: 2023
	},
	{
		name: 'Master Egg Hunter',
		notes: '10% item drop / passive',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['item'],
		year: 2024
	},
	{
		name: 'Attract Snakes',
		notes: '5% combat frequency / 10 turns / 50 MP',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['misc'],
		year: 2024
	},
	{
		name: 'Hide From Seekers',
		notes: '-5% combat frequency / 10 turns / 50 MP',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['misc'],
		year: 2024
	},
	{
		name: 'Holiday Multitasking',
		notes: '3 free crafts / day / passive',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['misc', 'marginal'],
		year: 2024
	},
	{
		name: 'Reindeer Games',
		notes: '30% combat initiative / passive',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['init'],
		year: 2024
	},
	{
		name: 'Crimbo Training: Concierge',
		notes: '+1 familiar weight',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['familiar', 'xp', 'item', 'meat', 'marginal'],
		year: 2022
	},
	{
		name: 'Crimbo Training: Bartender',
		notes: '+15% Booze Drops from Monsterst',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['item', 'marginal'],
		year: 2022
	},
	{
		name: 'Crimbo Training: Night Watchman',
		notes: 'Slight Spooky Resistance (+1)',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['combat', 'marginal'],
		year: 2022
	},
	{
		name: 'Secret Door Awareness',
		notes: 'scroll of minor invulnerability',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['misc'],
		year: 2023
	},
	{
		name: 'Silent Hunter',
		notes: '+100% initiative',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['init'],
		year: 2017
	},
	{
		name: 'Crimbo Training: Coal Taster',
		notes: 'Slight Hot Resistance (+1)',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['combat', 'marginal'],
		year: 2022
	},
	{
		name: 'Shrap',
		notes: 'Physical combat spell',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['combat', 'marginal'],
		year: 2013
	},
	{
		name: 'Budget Conscious',
		notes: 'Meat',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['meat', 'marginal'],
		year: 2018
	},
	{
		name: 'Acquire Rhinestones',
		notes: 'Tiny moxie buff',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['combat', 'marginal'],
		year: 2018
	},
	{
		name: 'Carol of the Bulls',
		notes: 'Weapon damage',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['combat', 'marginal'],
		year: 2018
	},
	{
		name: 'Carol of the Hells',
		notes: 'Spell damage',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['combat', 'marginal'],
		year: 2018
	},
	{
		name: 'Carol of the Thrills',
		notes: '+3 Stats Per Fight',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['xp', 'marginal'],
		year: 2018
	},
	{
		name: 'Chip on your Shoulder',
		notes: '+5 PvP fight(s) per day',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['evergreen', 'marginal'],
		year: null
	},
	{
		name: 'Drinking to Drink',
		notes: '+1 liver capacity',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['turns', 'marginal'],
		year: 2018
	},
	{
		name: 'Eggsplosion',
		notes: 'Stench spell',
		source: SkillSource.HOBOPOLIS,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['combat', 'evergreen', 'marginal'],
		year: null
	},
	{
		name: 'Gallapagosian Mating Call',
		notes: 'Adds 1 copy of the monster to the zone until rollover or used on something else.',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['turns'],
		year: 2018
	},
	{
		name: 'Get Big',
		notes: 'Muscle +20% Mysticality +20% Moxie +20%',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['combat'],
		year: 2018
	},
	{
		name: 'Grease Lightning',
		notes: 'Sleaze spell',
		source: SkillSource.HOBOPOLIS,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['combat'],
		year: 2018
	},
	{
		name: "Inigo's Incantation of Inspiration",
		notes: 'Lets you craft things more quickly',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['turns', 'marginal'],
		year: 2010
	},
	{
		name: 'Inscrutable Gaze',
		notes: '+10% to all Mysticality Gains',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['xp', 'marginal'],
		year: 2018
	},
	{
		name: 'Just the Facts',
		notes: 'meat',
		source: SkillSource.IOTM,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['turns'],
		year: 2018
	},
	{
		name: 'Love Mixology',
		notes: 'Weird potion',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['combat', 'marginal'],
		year: 2018
	},
	{
		name: 'Master of the Surprising Fist',
		notes: 'Weapon Damage +10 Damage Reduction: 10 (only with empty hands)',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['combat', 'marginal'],
		year: 2011
	},
	{
		name: 'Natural Born Skeleton Killer',
		notes: '+10% Damage vs. Skeletons',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: false,
		tags: ['combat', 'marginal'],
		year: 2011
	},
	{
		name: "Paul's Passionate Pop Song",
		notes: 'Regenerate 4-5 MP per Adventure',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['mp', 'marginal'],
		year: 2018
	},
	{
		name: 'Vent Rage Gland',
		notes: 'Passive damage',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['combat', 'marginal'],
		year: 2009
	},
	{
		name: 'Only Dogs Love a Drunken Sailor',
		notes: '5 familiar weight / 10 turns',
		source: SkillSource.SKILLBOOK,
		class: null,
		level: null,
		sc: true,
		hc: true,
		tags: ['familiar', 'xp', 'item', 'meat'],
		year: 2025
	}
];
